### ISSUE TITLE
ubsan: warning in clock code

### ISSUE THREAD

**Issue by shenki** [openbmc/linux#145]
e156398
v4.16-rc6-119-ge156398bfcad

from Joel's experimental 4.16 tree, on a qemu romulus machine

```
[   19.489529] ================================================================================
[   19.489694] UBSAN: Undefined behaviour in drivers/clk/clk-aspeed.c:214:12
[   19.490181] shift exponent -1 is negative
[   19.490645] CPU: 0 PID: 1 Comm: swapper Not tainted 4.16.0-rc6-00118-g671c39af8e7d-dirty #269
[   19.490770] Hardware name: Generic DT based system
[   19.491348] [<80016978>] (unwind_backtrace) from [<80012af8>] (show_stack+0x20/0x24)
[   19.491554] [<80012af8>] (show_stack) from [<80929cfc>] (dump_stack+0x20/0x28)
[   19.491695] [<80929cfc>] (dump_stack) from [<8049a178>] (ubsan_epilogue+0x14/0x60)
[   19.491836] [<8049a178>] (ubsan_epilogue) from [<8049ac14>] (__ubsan_handle_shift_out_of_bounds+0x198/0x1c8)
[   19.491973] [<8049ac14>] (__ubsan_handle_shift_out_of_bounds) from [<804cf3ec>] (aspeed_clk_enable+0x1c8/0x210)
[   19.492103] [<804cf3ec>] (aspeed_clk_enable) from [<804c1d74>] (clk_core_enable+0xe0/0x274)
[   19.492233] [<804c1d74>] (clk_core_enable) from [<804c6584>] (clk_register+0xa20/0xe50)
[   19.492365] [<804c6584>] (clk_register) from [<804c69cc>] (clk_hw_register+0x18/0x24)
[   19.492487] [<804c69cc>] (clk_hw_register) from [<804cf880>] (aspeed_clk_probe+0x44c/0x6cc)
[   19.492656] [<804cf880>] (aspeed_clk_probe) from [<8051bb50>] (platform_drv_probe+0x88/0x170)
[   19.492781] [<8051bb50>] (platform_drv_probe) from [<80518418>] (driver_probe_device+0x484/0x908)
[   19.492898] [<80518418>] (driver_probe_device) from [<805189b8>] (__driver_attach+0x11c/0x180)
[   19.493009] [<805189b8>] (__driver_attach) from [<805145c8>] (bus_for_each_dev+0xb0/0x104)
[   19.493125] [<805145c8>] (bus_for_each_dev) from [<80518cd8>] (driver_attach+0x38/0x54)
[   19.493234] [<80518cd8>] (driver_attach) from [<8051572c>] (bus_add_driver+0x1ec/0x3f8)
[   19.493374] [<8051572c>] (bus_add_driver) from [<8051a0bc>] (driver_register+0xe4/0x1c8)
[   19.493513] [<8051a0bc>] (driver_register) from [<8051ccc4>] (__platform_driver_register+0x74/0x9c)
[   19.493673] [<8051ccc4>] (__platform_driver_register) from [<80b3ee8c>] (aspeed_clk_driver_init+0x20/0x28)
[   19.493821] [<80b3ee8c>] (aspeed_clk_driver_init) from [<80b18574>] (do_one_initcall+0x15c/0x260)
[   19.493946] [<80b18574>] (do_one_initcall) from [<80b1891c>] (kernel_init_freeable+0x2a4/0x388)
[   19.494087] [<80b1891c>] (kernel_init_freeable) from [<8094feb4>] (kernel_init+0x1c/0x124)
[   19.494223] [<8094feb4>] (kernel_init) from [<800090f0>] (ret_from_fork+0x14/0x24)
[   19.494339] Exception stack(0x97d03fb0 to 0x97d03ff8)
[   19.494607] 3fa0:                                     00000000 00000000 00000000 00000000
[   19.494915] 3fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[   19.495143] 3fe0: 00000000 00000000 00000000 00000000 00000013 00000000
[   19.495289] ================================================================================
```

**Comment by shenki** [comment]
I think the issue is we calculate `BIT(gate->reset_idx)` unconditnally, outside of the check for `reset_idx >= 0`.

Assuming this is the case, the bad value is never used. The code could be refactored to not do this to avoid the warning.

**Comment by shenki** [comment]
```
#1  0x804cf3ec in aspeed_clk_enable (hw=0x97d65b40) at drivers/clk/clk-aspeed.c:214
        reg = 2547006412
        clk = 4
#2  0x804c1d74 in clk_core_enable (core=0x91d82c00) at drivers/clk/clk.c:881
        ret = 0
#3  0x804c6584 in __clk_core_init (core=<optimized out>) at drivers/clk/clk.c:3009
        flags = 2684354643
        i = -1610612653
        orphan = 0xa0000053
        rate = 0
        tmp2 = 0x0
        descriptor = {modname = 0x80a79bb8 "clk", function = 0x80989794 <__func__.40039> "__clk_core_init", 
          filename = 0x80a79344 "drivers/clk/clk.c", format = 0x80a79714 "%s: clk %s already initialized\n", lineno = 2863, flags = 0, 
          key = {dd_key_true = <incomplete type>, dd_key_false = <incomplete type>}}
#4  clk_register (dev=0x0, hw=0x97d65b40) at drivers/clk/clk.c:3141
No locals.
#5  0x804c69cc in clk_hw_register (dev=0x80d21340, hw=0x1) at drivers/clk/clk.c:3176
No locals.
#6  0x804cf880 in aspeed_clk_hw_register_gate (lock=<optimized out>, clk_gate_flags=<optimized out>, reset_idx=<optimized out>, 
    clock_idx=<optimized out>, map=<optimized out>, flags=<optimized out>, parent_name=0x80a7a1c4 "mpll", name=<optimized out>, 
    dev=<optimized out>) at drivers/clk/clk-aspeed.c:377
        init = <incomplete type>
        hw = 0xffffffff
        ret = 1
#7  aspeed_clk_probe (pdev=0xffffffff) at drivers/clk/clk-aspeed.c:503
        soc_data = 0x8098a3a8 <aspeed_gates+32>
        dev = 0x1
        map = 0x80a7a20c
        val = 197265
        rate = 2547006344
        i = 2
```

it looks to be due to the registering of `mclk-gate`.
